# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 06:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(verbose_name='\u5b66\u671f')),
                ('course_type', models.CharField(choices=[('online', '\u7f51\u7edc\u73ed'), ('offline_weekend', '\u9762\u6388\u73ed\uff08\u5468\u672b\uff09'), ('offline_fulltime', '\u9762\u6388\u73ed\uff08\u8131\u4ea7\uff09')], default='offline_weekend', max_length=64)),
                ('start_date', models.DateField()),
                ('graduate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('online_price', models.IntegerField()),
                ('offline_price', models.IntegerField()),
                ('introduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(verbose_name='\u7b2c\u51e0\u8282\u8bfe')),
                ('course_date', models.DateField(auto_now_add=True, verbose_name='\u4e0a\u8bfe\u65f6\u95f4')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClassList')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('course_type', models.CharField(choices=[('online', '\u7f51\u7edc\u73ed'), ('offline_weekend', '\u9762\u6388\u73ed\uff08\u5468\u672b\uff09'), ('offline_fulltime', '\u9762\u6388\u73ed\uff08\u8131\u4ea7\uff09')], default='offline_weekend', max_length=64)),
                ('consult_memo', models.TextField()),
                ('source_type', models.CharField(choices=[('qq', 'qq\u7fa4'), ('referral', '\u5185\u90e8\u8f6c\u4ecb\u7ecd'), ('51cto', '51cto'), ('agent', '\u62db\u751f\u4ee3\u7406'), ('others', '\u5176\u4ed6')], max_length=64)),
                ('status', models.CharField(choices=[('signed', '\u5df2\u62a5\u540d'), ('unregistered', '\u672a\u62a5\u540d'), ('graduated', '\u5df2\u6bd5\u4e1a'), ('drop-off', '\u9000\u5b66')], max_length=64)),
                ('date', models.DateField(auto_now_add=True, verbose_name='\u54a8\u8be2\u65e5\u671f')),
                ('class_list', models.ManyToManyField(blank=True, to='crm.ClassList')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_record', models.TextField(verbose_name='\u8ddf\u8e2a\u8bb0\u5f55')),
                ('track_date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, '\u8fd1\u671f\u65e0\u62a5\u540d\u8ba1\u5212'), (2, '2\u4e2a\u6708\u5185\u62a5\u540d'), (3, '\u4e00\u4e2a\u6708\u5185\u62a5\u540d'), (4, '2\u5468\u5185\u62a5\u540d'), (5, '1\u5468\u5185\u62a5\u540d'), (6, '2\u5929\u5185\u62a5\u540d'), (7, '\u5df2\u62a5\u540d')], help_text='\u9009\u62e9\u5ba2\u6237\u6b64', verbose_name='\u72b6\u6001')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('city', models.CharField(max_length=64)),
                ('addr', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[('checked', '\u5df2\u7b7e\u5230'), ('late', '\u8fdf\u5230'), ('noshow', '\u7f3a\u52e4'), ('leave_early', '\u65e9\u9000')], default='checked', max_length=64, verbose_name='\u72b6\u6001')),
                ('score', models.IntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (0, 'D'), (-1, 'N/A'), (-100, 'COPY'), (-1000, 'FAIL')], default=-1, verbose_name='\u672c\u8282\u6210\u7ee9')),
                ('date', models.DateField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('course_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.CourseRecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.School')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customertrackrecord',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='\u8bfe\u7a0b\u987e\u95ee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course'),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_who', to='crm.Customer'),
        ),
        migrations.AddField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Course', verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='classlist',
            name='teachers',
            field=models.ManyToManyField(to='crm.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='courserecord',
            unique_together=set([('class_obj', 'day_num')]),
        ),
        migrations.AlterUniqueTogether(
            name='classlist',
            unique_together=set([('course', 'semester', 'course_type')]),
        ),
    ]
