# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170809_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '\u53ef\u4ee5\u67e5\u770b\u5ba2\u6237\u5217\u8868'), ('view_customer_info', '\u53ef\u4ee5\u67e5\u770b\u5ba2\u6237\u8be6\u7ec6\u4fe1\u606f'), ('edit_own_customer_info', '\u53ef\u4ee5\u4fee\u6539\u81ea\u5df1\u7684\u5ba2\u6237\u4fe1\u606f'))},
        ),
    ]
