# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sansa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='bussiness_unit',
            new_name='business_unit',
        ),
        migrations.AlterField(
            model_name='asset',
            name='manufactory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sansa.Manufactory', verbose_name='制造商'),
        ),
    ]
