# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '\u4f5c\u8005'},
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[(b'published', '\u5df2\u51fa\u7248'), (b'producing', '\u5f85\u51fa\u7248'), (b'forbidden', '\u7981\u4e66')], default=b'producing', max_length=32),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(help_text=b'write your country here.', max_length=50, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe7\x9c\x81'),
        ),
    ]
