# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commet_type',
            new_name='comment_type',
        ),
    ]
