# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0004_auto_20170810_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='postition_index',
            new_name='position_index',
        ),
    ]
